AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Dynamic Static Website using S3 + CloudFront with custom domain and ACM certificate.

Parameters:

  BucketName:
    Type: String
    Description: "Name of the S3 bucket for the website"

  IndexDocument:
    Type: String
    Default: index.html
    Description: "Default index document"

  ErrorDocument:
    Type: String
    Default: error.html
    Description: "Error document"

  CertificateArn:
    Type: String
    Description: "ACM certificate ARN (must be issued in us-east-1)"

  DomainName:
    Type: String
    Description: "Custom domain name for CloudFront"

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: !Ref IndexDocument
        ErrorDocument: !Ref ErrorDocument
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${WebsiteBucket.Arn}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: !Ref IndexDocument
        Origins:
          - Id: S3WebsiteOrigin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3WebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
        Aliases:
          - !Ref DomainName

Outputs:

  S3WebsiteURL:
    Description: "S3 static website URL"
    Value: !GetAtt WebsiteBucket.WebsiteURL

  CloudFrontURL:
    Description: "CloudFront HTTPS URL"
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
