AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Dynamic Static Website using S3 + CloudFront without a custom domain.
  All names and files are configurable via parameters.

Parameters:

  BucketName:
    Type: String
    Description: "Name of the S3 bucket to create for the website"

  IndexDocument:
    Type: String
    Default: index.html
    Description: "Default index document for S3 website"

  ErrorDocument:
    Type: String
    Default: error.html
    Description: "Error document for S3 website"

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: !Ref IndexDocument
        ErrorDocument: !Ref ErrorDocument
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${WebsiteBucket.Arn}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: !Ref IndexDocument

        Origins:
          - Id: S3WebsiteOrigin
            DomainName: !Select
              - 2
              - !Split
                - "/"
                - !GetAtt WebsiteBucket.WebsiteURL
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only

        DefaultCacheBehavior:
          TargetOriginId: S3WebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false

        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:

  S3WebsiteURL:
    Description: "S3 static website URL"
    Value: !GetAtt WebsiteBucket.WebsiteURL

  CloudFrontURL:
    Description: "CloudFront HTTPS URL"
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
